const express = require("express");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 3000;

// Serve static files from public directory
app.use(express.static("public"));

// Serve the main HTML file
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

// API endpoint for Mongolian data
app.get("/api/mongolian-data", (req, res) => {
  const mongolianData = {
    alphabet: {
      cyrillic: [
        {
          letter: "А",
          pronunciation: "A",
          ipa: "a",
          example: "Алт (Alt) - Gold",
        },
        {
          letter: "Б",
          pronunciation: "B",
          ipa: "b",
          example: "Байр (Bair) - Place",
        },
        {
          letter: "В",
          pronunciation: "V",
          ipa: "v",
          example: "Ван (Van) - King",
        },
        {
          letter: "Г",
          pronunciation: "G",
          ipa: "ɡ",
          example: "Гэр (Ger) - House",
        },
        {
          letter: "Д",
          pronunciation: "D",
          ipa: "d",
          example: "Дээд (Deed) - Upper",
        },
        {
          letter: "Е",
          pronunciation: "Ye",
          ipa: "je",
          example: "Ерөнхий (Yeronkhii) - General",
        },
        {
          letter: "Ё",
          pronunciation: "Yo",
          ipa: "jo",
          example: "Ёс (Yos) - Custom",
        },
        {
          letter: "Ж",
          pronunciation: "J",
          ipa: "dʒ",
          example: "Жаргал (Jargal) - Happiness",
        },
        {
          letter: "З",
          pronunciation: "Z",
          ipa: "z",
          example: "Зай (Zai) - Distance",
        },
        {
          letter: "И",
          pronunciation: "I",
          ipa: "i",
          example: "Их (Ikh) - Big",
        },
        {
          letter: "Й",
          pronunciation: "Y",
          ipa: "j",
          example: "Йлд (Yld) - Weapon",
        },
        {
          letter: "К",
          pronunciation: "K",
          ipa: "k",
          example: "Кино (Kino) - Movie",
        },
        {
          letter: "Л",
          pronunciation: "L",
          ipa: "l",
          example: "Лам (Lam) - Monk",
        },
        {
          letter: "М",
          pronunciation: "M",
          ipa: "m",
          example: "Мал (Mal) - Livestock",
        },
        {
          letter: "Н",
          pronunciation: "N",
          ipa: "n",
          example: "Ном (Nom) - Book",
        },
        {
          letter: "О",
          pronunciation: "O",
          ipa: "ɔ",
          example: "Орд (Ord) - Palace",
        },
        {
          letter: "Ө",
          pronunciation: "Ö",
          ipa: "ɵ",
          example: "Өргөө (Örgöö) - Palace",
        },
        {
          letter: "П",
          pronunciation: "P",
          ipa: "p",
          example: "Парк (Park) - Park",
        },
        {
          letter: "Р",
          pronunciation: "R",
          ipa: "r",
          example: "Радио (Radio) - Radio",
        },
        {
          letter: "С",
          pronunciation: "S",
          ipa: "s",
          example: "Сайхан (Saikhan) - Beautiful",
        },
        {
          letter: "Т",
          pronunciation: "T",
          ipa: "t",
          example: "Тэнгэр (Tenger) - Sky",
        },
        {
          letter: "У",
          pronunciation: "U",
          ipa: "ʊ",
          example: "Улаан (Ulaan) - Red",
        },
        {
          letter: "Ү",
          pronunciation: "Ü",
          ipa: "u",
          example: "Үнэ (Üne) - Price",
        },
        {
          letter: "Ф",
          pronunciation: "F",
          ipa: "f",
          example: "Фабрик (Fabrik) - Factory",
        },
        {
          letter: "Х",
          pronunciation: "Kh",
          ipa: "x",
          example: "Хүн (Khün) - Person",
        },
        {
          letter: "Ц",
          pronunciation: "Ts",
          ipa: "ts",
          example: "Цагаан (Tsagaan) - White",
        },
        {
          letter: "Ч",
          pronunciation: "Ch",
          ipa: "tʃ",
          example: "Чулуу (Chuluu) - Stone",
        },
        {
          letter: "Ш",
          pronunciation: "Sh",
          ipa: "ʃ",
          example: "Шар (Shar) - Yellow",
        },
        {
          letter: "Щ",
          pronunciation: "Shch",
          ipa: "ʃtʃ",
          example: "Щавель (Shchavel) - Sorrel",
        },
        {
          letter: "Ъ",
          pronunciation: "Hard sign",
          ipa: "",
          example: "Ъе (Ye) - Yes",
        },
        {
          letter: "Ы",
          pronunciation: "Y",
          ipa: "ɨ",
          example: "Ынх (Ynh) - Goat",
        },
        {
          letter: "Ь",
          pronunciation: "Soft sign",
          ipa: "",
          example: "Ьө (Yö) - Yes",
        },
        {
          letter: "Э",
          pronunciation: "E",
          ipa: "e",
          example: "Эрдэнэ (Erdene) - Jewel",
        },
        {
          letter: "Ю",
          pronunciation: "Yu",
          ipa: "ju",
          example: "Юм (Yum) - Thing",
        },
        {
          letter: "Я",
          pronunciation: "Ya",
          ipa: "ja",
          example: "Ямаа (Yamaa) - Goat",
        },
      ],
    },
    numbers: [
      {
        number: 1,
        mongolian: "нэг",
        pronunciation: "neg",
        ipa: "neg",
        english: "one",
      },
      {
        number: 2,
        mongolian: "хоёр",
        pronunciation: "khoyor",
        ipa: "xɔjɔr",
        english: "two",
      },
      {
        number: 3,
        mongolian: "гурав",
        pronunciation: "gurav",
        ipa: "ɡʊrav",
        english: "three",
      },
      {
        number: 4,
        mongolian: "дөрөв",
        pronunciation: "döröv",
        ipa: "dɵrɵv",
        english: "four",
      },
      {
        number: 5,
        mongolian: "тав",
        pronunciation: "tav",
        ipa: "tav",
        english: "five",
      },
      {
        number: 6,
        mongolian: "зургаа",
        pronunciation: "zurgaa",
        ipa: "zʊrɡaː",
        english: "six",
      },
      {
        number: 7,
        mongolian: "долоо",
        pronunciation: "doloo",
        ipa: "dɔlɔː",
        english: "seven",
      },
      {
        number: 8,
        mongolian: "найм",
        pronunciation: "naim",
        ipa: "naim",
        english: "eight",
      },
      {
        number: 9,
        mongolian: "ес",
        pronunciation: "yes",
        ipa: "jes",
        english: "nine",
      },
      {
        number: 10,
        mongolian: "арав",
        pronunciation: "arav",
        ipa: "arav",
        english: "ten",
      },
      {
        number: 11,
        mongolian: "арван нэг",
        pronunciation: "arvan neg",
        ipa: "arvan neg",
        english: "eleven",
      },
      {
        number: 12,
        mongolian: "арван хоёр",
        pronunciation: "arvan khoyor",
        ipa: "arvan xɔjɔr",
        english: "twelve",
      },
      {
        number: 13,
        mongolian: "арван гурав",
        pronunciation: "arvan gurav",
        ipa: "arvan ɡʊrav",
        english: "thirteen",
      },
      {
        number: 14,
        mongolian: "арван дөрөв",
        pronunciation: "arvan döröv",
        ipa: "arvan dɵrɵv",
        english: "fourteen",
      },
      {
        number: 15,
        mongolian: "арван тав",
        pronunciation: "arvan tav",
        ipa: "arvan tav",
        english: "fifteen",
      },
      {
        number: 16,
        mongolian: "арван зургаа",
        pronunciation: "arvan zurgaa",
        ipa: "arvan zʊrɡaː",
        english: "sixteen",
      },
      {
        number: 17,
        mongolian: "арван долоо",
        pronunciation: "arvan doloo",
        ipa: "arvan dɔlɔː",
        english: "seventeen",
      },
      {
        number: 18,
        mongolian: "арван найм",
        pronunciation: "arvan naim",
        ipa: "arvan naim",
        english: "eighteen",
      },
      {
        number: 19,
        mongolian: "арван ес",
        pronunciation: "arvan yes",
        ipa: "arvan jes",
        english: "nineteen",
      },
      {
        number: 20,
        mongolian: "хорин",
        pronunciation: "khorin",
        ipa: "xɔrin",
        english: "twenty",
      },
    ],
    basicWords: [
      {
        mongolian: "Сайн байна уу",
        pronunciation: "Sain baina uu",
        ipa: "sain baina uː",
        english: "Hello/How are you?",
      },
      {
        mongolian: "Баяртай",
        pronunciation: "Bayartai",
        ipa: "bajartai",
        english: "Goodbye",
      },
      {
        mongolian: "Баярлалаа",
        pronunciation: "Bayarlalaa",
        ipa: "bajarlalaː",
        english: "Thank you",
      },
      { mongolian: "Тийм", pronunciation: "Tiim", ipa: "tiːm", english: "Yes" },
      { mongolian: "Үгүй", pronunciation: "Ügüi", ipa: "uɡui", english: "No" },
      {
        mongolian: "Уучлаарай",
        pronunciation: "Uuchlaarai",
        ipa: "uːtʃlaːrai",
        english: "Sorry/Excuse me",
      },
      { mongolian: "Би", pronunciation: "Bi", ipa: "bi", english: "I/Me" },
      {
        mongolian: "Та",
        pronunciation: "Ta",
        ipa: "ta",
        english: "You (formal)",
      },
      {
        mongolian: "Чи",
        pronunciation: "Chi",
        ipa: "tʃi",
        english: "You (informal)",
      },
      { mongolian: "Ус", pronunciation: "Us", ipa: "ʊs", english: "Water" },
      {
        mongolian: "Хоол",
        pronunciation: "Khuul",
        ipa: "xuːl",
        english: "Food",
      },
      {
        mongolian: "Гэр",
        pronunciation: "Ger",
        ipa: "ɡer",
        english: "House/Yurt",
      },
      {
        mongolian: "Мал",
        pronunciation: "Mal",
        ipa: "mal",
        english: "Livestock",
      },
      {
        mongolian: "Тэнгэр",
        pronunciation: "Tenger",
        ipa: "teŋɡer",
        english: "Sky",
      },
      {
        mongolian: "Газрын",
        pronunciation: "Gazryn",
        ipa: "ɡazrin",
        english: "Earth",
      },
    ],
    travelPhrases: [
      {
        mongolian: "Сайн байна уу",
        pronunciation: "Sain baina uu",
        ipa: "sain baina uː",
        english: "Hello/How are you?",
      },
      {
        mongolian: "Баяртай",
        pronunciation: "Bayartai",
        ipa: "bajartai",
        english: "Goodbye",
      },
      {
        mongolian: "Баярлалаа",
        pronunciation: "Bayarlalaa",
        ipa: "bajarlalaː",
        english: "Thank you",
      },
      {
        mongolian: "Уучлаарай",
        pronunciation: "Uuchlaarai",
        ipa: "uːtʃlaːrai",
        english: "Sorry/Excuse me",
      },
      {
        mongolian: "Би ойлгохгүй байна",
        pronunciation: "Bi oilgokhgüi baina",
        ipa: "bi ɔilɡɔxɡui baina",
        english: "I don't understand",
      },
      {
        mongolian: "Та англи хэл мэдэх үү?",
        pronunciation: "Ta angli khel medekh üü?",
        ipa: "ta aŋɡli xel medex üː",
        english: "Do you speak English?",
      },
      {
        mongolian: "Би гадаадын хүн",
        pronunciation: "Bi gadaadyn khün",
        ipa: "bi ɡadaːdyn xun",
        english: "I am a foreigner",
      },
      {
        mongolian: "Би аялж байна",
        pronunciation: "Bi ayalj baina",
        ipa: "bi ajaldʒ baina",
        english: "I am traveling",
      },
      {
        mongolian: "Энэ хэдэн төгрөг вэ?",
        pronunciation: "Ene kheden tögrög ve?",
        ipa: "ene xeden tɵɡrɵɡ ve",
        english: "How much is this?",
      },
      {
        mongolian: "Хэт үнэтэй байна",
        pronunciation: "Khet ünetei baina",
        ipa: "xet ünetei baina",
        english: "It's too expensive",
      },
      {
        mongolian: "Хямд уу?",
        pronunciation: "Khyamd uu?",
        ipa: "xjamd uː",
        english: "Is it cheap?",
      },
      {
        mongolian: "Хаана байна?",
        pronunciation: "Khaana baina?",
        ipa: "xaːna baina",
        english: "Where is it?",
      },
      {
        mongolian: "Энэ хаана байна?",
        pronunciation: "Ene khaana baina?",
        ipa: "ene xaːna baina",
        english: "Where is this?",
      },
      {
        mongolian: "Би явж байна",
        pronunciation: "Bi yavj baina",
        ipa: "bi javdʒ baina",
        english: "I am going",
      },
      {
        mongolian: "Би ирж байна",
        pronunciation: "Bi irj baina",
        ipa: "bi irdʒ baina",
        english: "I am coming",
      },
      {
        mongolian: "Би сууж байна",
        pronunciation: "Bi suuj baina",
        ipa: "bi suːdʒ baina",
        english: "I am sitting",
      },
      {
        mongolian: "Би зөөж байна",
        pronunciation: "Bi zööj baina",
        ipa: "bi zɵːdʒ baina",
        english: "I am carrying",
      },
      {
        mongolian: "Би харж байна",
        pronunciation: "Bi kharj baina",
        ipa: "bi xardʒ baina",
        english: "I am looking",
      },
      {
        mongolian: "Би сонсож байна",
        pronunciation: "Bi sonsoj baina",
        ipa: "bi sɔnsɔdʒ baina",
        english: "I am listening",
      },
      {
        mongolian: "Би идэж байна",
        pronunciation: "Bi idej baina",
        ipa: "bi idedʒ baina",
        english: "I am eating",
      },
      {
        mongolian: "Би ууж байна",
        pronunciation: "Bi uuj baina",
        ipa: "bi uːdʒ baina",
        english: "I am drinking",
      },
      {
        mongolian: "Би унтаж байна",
        pronunciation: "Bi untaj baina",
        ipa: "bi untadʒ baina",
        english: "I am sleeping",
      },
      {
        mongolian: "Би ажиллаж байна",
        pronunciation: "Bi ajillaj baina",
        ipa: "bi adʒilladʒ baina",
        english: "I am working",
      },
      {
        mongolian: "Би сурч байна",
        pronunciation: "Bi surch baina",
        ipa: "bi surtʃ baina",
        english: "I am studying",
      },
      {
        mongolian: "Би тоглож байна",
        pronunciation: "Bi togloj baina",
        ipa: "bi tɔɡlɔdʒ baina",
        english: "I am playing",
      },
      {
        mongolian: "Би дуулж байна",
        pronunciation: "Bi duulj baina",
        ipa: "bi duːldʒ baina",
        english: "I am singing",
      },
      {
        mongolian: "Би бүжиглэж байна",
        pronunciation: "Bi büjiglej baina",
        ipa: "bi budʒiɡledʒ baina",
        english: "I am dancing",
      },
    ],
    essentialVerbs: [
      {
        mongolian: "Явах",
        pronunciation: "Yavakh",
        ipa: "javax",
        english: "To go",
        present: "явж байна",
        past: "явсан",
        future: "явах",
      },
      {
        mongolian: "Ирэх",
        pronunciation: "Irekh",
        ipa: "irex",
        english: "To come",
        present: "ирж байна",
        past: "ирсэн",
        future: "ирэх",
      },
      {
        mongolian: "Суух",
        pronunciation: "Suukh",
        ipa: "suːx",
        english: "To sit",
        present: "сууж байна",
        past: "суусан",
        future: "суух",
      },
      {
        mongolian: "Зөөх",
        pronunciation: "Zöökh",
        ipa: "zɵːx",
        english: "To carry",
        present: "зөөж байна",
        past: "зөөсөн",
        future: "зөөх",
      },
      {
        mongolian: "Харах",
        pronunciation: "Kharakh",
        ipa: "xarax",
        english: "To look",
        present: "харж байна",
        past: "харсан",
        future: "харах",
      },
      {
        mongolian: "Сонсох",
        pronunciation: "Sonsokh",
        ipa: "sɔnsɔx",
        english: "To listen",
        present: "сонсож байна",
        past: "сонссон",
        future: "сонсох",
      },
      {
        mongolian: "Идэх",
        pronunciation: "Idek",
        ipa: "idex",
        english: "To eat",
        present: "идэж байна",
        past: "идсэн",
        future: "идэх",
      },
      {
        mongolian: "Уух",
        pronunciation: "Uukh",
        ipa: "uːx",
        english: "To drink",
        present: "ууж байна",
        past: "уусан",
        future: "уух",
      },
      {
        mongolian: "Унтах",
        pronunciation: "Untakh",
        ipa: "untax",
        english: "To sleep",
        present: "унтаж байна",
        past: "унтсан",
        future: "унтах",
      },
      {
        mongolian: "Ажиллах",
        pronunciation: "Ajillakh",
        ipa: "adʒillax",
        english: "To work",
        present: "ажиллаж байна",
        past: "ажилласан",
        future: "ажиллах",
      },
      {
        mongolian: "Сурх",
        pronunciation: "Surkh",
        ipa: "surx",
        english: "To study",
        present: "сурч байна",
        past: "сурсан",
        future: "сурх",
      },
      {
        mongolian: "Тоглох",
        pronunciation: "Toglokh",
        ipa: "tɔɡlɔx",
        english: "To play",
        present: "тоглож байна",
        past: "тоглосон",
        future: "тоглох",
      },
      {
        mongolian: "Дуулах",
        pronunciation: "Duulakh",
        ipa: "duːlax",
        english: "To sing",
        present: "дуулж байна",
        past: "дуулсан",
        future: "дуулах",
      },
      {
        mongolian: "Бүжиглэх",
        pronunciation: "Büjiglekh",
        ipa: "budʒiɡlex",
        english: "To dance",
        present: "бүжиглэж байна",
        past: "бүжиглэсэн",
        future: "бүжиглэх",
      },
      {
        mongolian: "Бичих",
        pronunciation: "Bichikh",
        ipa: "bitʃix",
        english: "To write",
        present: "бичиж байна",
        past: "бичсэн",
        future: "бичих",
      },
      {
        mongolian: "Унших",
        pronunciation: "Unshikh",
        ipa: "unʃix",
        english: "To read",
        present: "уншиж байна",
        past: "уншсан",
        future: "унших",
      },
      {
        mongolian: "Хэлэх",
        pronunciation: "Khelekh",
        ipa: "xelex",
        english: "To speak",
        present: "хэлж байна",
        past: "хэлсэн",
        future: "хэлэх",
      },
      {
        mongolian: "Ойлгох",
        pronunciation: "Oilgokh",
        ipa: "ɔilɡɔx",
        english: "To understand",
        present: "ойлгож байна",
        past: "ойлгосон",
        future: "ойлгох",
      },
      {
        mongolian: "Хүсэх",
        pronunciation: "Khüsekh",
        ipa: "xusex",
        english: "To want",
        present: "хүсэж байна",
        past: "хүссэн",
        future: "хүсэх",
      },
    ],
    travelVocabulary: [
      {
        mongolian: "Зочид буудал",
        pronunciation: "Zochid buudal",
        ipa: "zɔtʃid buːdal",
        english: "Hotel",
      },
      {
        mongolian: "Ресторан",
        pronunciation: "Restoran",
        ipa: "restɔran",
        english: "Restaurant",
      },
      {
        mongolian: "Хоол",
        pronunciation: "Khuul",
        ipa: "xuːl",
        english: "Food",
      },
      { mongolian: "Ус", pronunciation: "Us", ipa: "ʊs", english: "Water" },
      { mongolian: "Цай", pronunciation: "Tsai", ipa: "tsai", english: "Tea" },
      {
        mongolian: "Кофе",
        pronunciation: "Kofe",
        ipa: "kɔfe",
        english: "Coffee",
      },
      {
        mongolian: "Мөнгө",
        pronunciation: "Möngö",
        ipa: "mɵŋɡɵ",
        english: "Money",
      },
      {
        mongolian: "Төгрөг",
        pronunciation: "Tögrög",
        ipa: "tɵɡrɵɡ",
        english: "Tugrik (currency)",
      },
      { mongolian: "Үнэ", pronunciation: "Üne", ipa: "üne", english: "Price" },
      {
        mongolian: "Хямд",
        pronunciation: "Khyamd",
        ipa: "xjamd",
        english: "Cheap",
      },
      {
        mongolian: "Үнэтэй",
        pronunciation: "Ünetei",
        ipa: "ünetei",
        english: "Expensive",
      },
      {
        mongolian: "Зах",
        pronunciation: "Zakh",
        ipa: "zax",
        english: "Market",
      },
      {
        mongolian: "Дэлгүүр",
        pronunciation: "Delgüür",
        ipa: "delɡüːr",
        english: "Shop",
      },
      {
        mongolian: "Эмнэлэг",
        pronunciation: "Emneleg",
        ipa: "emneleɡ",
        english: "Hospital",
      },
      { mongolian: "Эм", pronunciation: "Em", ipa: "em", english: "Medicine" },
      {
        mongolian: "Автобус",
        pronunciation: "Avtobus",
        ipa: "avtɔbus",
        english: "Bus",
      },
      {
        mongolian: "Такси",
        pronunciation: "Taksi",
        ipa: "taksi",
        english: "Taxi",
      },
      {
        mongolian: "Онгоц",
        pronunciation: "Ongots",
        ipa: "ɔŋɡɔts",
        english: "Airplane",
      },
      {
        mongolian: "Галт тэрэг",
        pronunciation: "Galt tereg",
        ipa: "ɡalt tereɡ",
        english: "Train",
      },
      { mongolian: "Зам", pronunciation: "Zam", ipa: "zam", english: "Road" },
      {
        mongolian: "Хаана",
        pronunciation: "Khaana",
        ipa: "xaːna",
        english: "Where",
      },
      {
        mongolian: "Хэзээ",
        pronunciation: "Khezee",
        ipa: "xezeː",
        english: "When",
      },
      {
        mongolian: "Яагаад",
        pronunciation: "Yaagaad",
        ipa: "jaːɡaːd",
        english: "Why",
      },
      { mongolian: "Юу", pronunciation: "Yuu", ipa: "juː", english: "What" },
      { mongolian: "Хэн", pronunciation: "Khen", ipa: "xen", english: "Who" },
      {
        mongolian: "Хэрхэн",
        pronunciation: "Kherkhen",
        ipa: "xerxen",
        english: "How",
      },
      {
        mongolian: "Хэдэн",
        pronunciation: "Kheden",
        ipa: "xeden",
        english: "How many",
      },
      {
        mongolian: "Хэд",
        pronunciation: "Khed",
        ipa: "xed",
        english: "How much",
      },
      { mongolian: "Энэ", pronunciation: "Ene", ipa: "ene", english: "This" },
      { mongolian: "Тэр", pronunciation: "Ter", ipa: "ter", english: "That" },
      { mongolian: "Энд", pronunciation: "End", ipa: "end", english: "Here" },
      {
        mongolian: "Тэнд",
        pronunciation: "Tend",
        ipa: "tend",
        english: "There",
      },
      { mongolian: "Одоо", pronunciation: "Odoo", ipa: "ɔdɔː", english: "Now" },
      {
        mongolian: "Өчигдөр",
        pronunciation: "Öchigdör",
        ipa: "ɵtʃiɡdɵr",
        english: "Yesterday",
      },
      {
        mongolian: "Маргааш",
        pronunciation: "Margaaш",
        ipa: "marɡaːʃ",
        english: "Tomorrow",
      },
      {
        mongolian: "Өнөөдөр",
        pronunciation: "Önöödör",
        ipa: "ɵnɵːdɵr",
        english: "Today",
      },
    ],
    romanticPhrases: [
      {
        mongolian: "Би чамд хайртай",
        pronunciation: "Bi chamd khairtai",
        ipa: "bi tʃamd xairtai",
        english: "I love you",
      },
      {
        mongolian: "Чи миний хайр",
        pronunciation: "Chi minii khair",
        ipa: "tʃi miniː xair",
        english: "You are my love",
      },
      {
        mongolian: "Чи сайхан харагдаж байна",
        pronunciation: "Chi saikhan kharagdaj baina",
        ipa: "tʃi saixan xaraɡdadʒ baina",
        english: "You look beautiful",
      },
      {
        mongolian: "Би чамайг хүсэж байна",
        pronunciation: "Bi chamaig khüsej baina",
        ipa: "bi tʃamaig xusedʒ baina",
        english: "I want you",
      },
      {
        mongolian: "Чи миний бүх зүйл",
        pronunciation: "Chi minii bükh züil",
        ipa: "tʃi miniː bux zui",
        english: "You are my everything",
      },
      {
        mongolian: "Би чамайг үнэрлэж байна",
        pronunciation: "Bi chamaig ünerlej baina",
        ipa: "bi tʃamaig unerledʒ baina",
        english: "I can smell you",
      },
      {
        mongolian: "Чи миний хүсэл",
        pronunciation: "Chi minii khüsel",
        ipa: "tʃi miniː xusel",
        english: "You are my desire",
      },
      {
        mongolian: "Би чамайг хүртэл хүсэж байна",
        pronunciation: "Bi chamaig khürtel khüsej baina",
        ipa: "bi tʃamaig xurtel xusedʒ baina",
        english: "I want to touch you",
      },
      {
        mongolian: "Чи миний хүн",
        pronunciation: "Chi minii khün",
        ipa: "tʃi miniː xun",
        english: "You are my person",
      },
      {
        mongolian: "Би чамайг үнсэж байна",
        pronunciation: "Bi chamaig ünsej baina",
        ipa: "bi tʃamaig unsedʒ baina",
        english: "I am kissing you",
      },
      {
        mongolian: "Чи миний амьдрал",
        pronunciation: "Chi minii amidral",
        ipa: "tʃi miniː amidral",
        english: "You are my life",
      },
      {
        mongolian: "Би чамайг хүндэтгэж байна",
        pronunciation: "Bi chamaig khündetgej baina",
        ipa: "bi tʃamaig xundetɡedʒ baina",
        english: "I respect you",
      },
      {
        mongolian: "Чи миний сэтгэл",
        pronunciation: "Chi minii setgel",
        ipa: "tʃi miniː setɡel",
        english: "You are my heart",
      },
      {
        mongolian: "Би чамайг хүндэлж байна",
        pronunciation: "Bi chamaig khündelj baina",
        ipa: "bi tʃamaig xundeldʒ baina",
        english: "I cherish you",
      },
      {
        mongolian: "Чи миний аз жаргал",
        pronunciation: "Chi minii az jargal",
        ipa: "tʃi miniː az dʒarɡal",
        english: "You are my happiness",
      },
    ],
  };

  res.json(mongolianData);
});

app.listen(PORT, () => {
  console.log(`Mongolian Learning App running on http://localhost:${PORT}`);
});
